# Generated by Django 3.0.8 on 2020-07-26 10:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=1024, null=True)),
                ('hash_value', models.CharField(max_length=20, null=True)),
                ('short_url', models.CharField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(0, 'init'), (1, 'live'), (2, 'blocked'), (3, 'expired')], default=0)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
